language: objective-c
osx_image: xcode8.3
before_install:
    - gem install xcpretty
script:
    - xcodebuild clean test -scheme 'ZamzamKit iOS' -project ZamzamKit.xcodeproj -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3.1" -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
    - xcodebuild clean test -scheme 'ZamzamKit tvOS' -project ZamzamKit.xcodeproj -destination "platform=tvOS Simulator,name=Apple TV 1080p" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
    - xcodebuild clean build -scheme 'ZamzamKit watchOS' -project ZamzamKit.xcodeproj CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
